In [ ]:
#Student Academic performance analysis

In [1]:

import pandas as pd

In [3]:
#Loading data
url = "https://raw.githubusercontent.com/ritaafrica/data/refs/heads/main/student_scores.csv"

In [4]:
df = pd.read_csv(url)

In [5]:
df

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3
...,...,...,...,...,...,...,...,...,...,...
95,96,Thabo Mensah,Tanzania,Male,17,31,86,75,Freedom College,SS1
96,97,Jelani Obasi,Nigeria,Female,15,75,3,62,Freedom College,JSS3
97,98,Abdi Okafor,Nigeria,Male,16,57,68,54,Freedom College,JSS1
98,99,Zanele Banda,Zambia,Female,17,74,20,44,Freedom College,JSS2
99,100,Thabo Kalema,Kenya,Male,18,14,33,72,Ubuntu Academy,JSS2

In [6]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3

In [7]:
#Adding an new column for total
df["Total_Score"] = df["Math_Score"] + df["Reading_Score"] + df["Writing_Score"]

In [9]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class,Total_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1,188
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2,187
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3,179
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2,136
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3,76

In [13]:
#Creating a percentage score column
df["Percentage_Score"] = (df["Total_Score"] / 300) * 100

In [14]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class,Total_Score,Percentage_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1,188,62.666667
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2,187,62.333333
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3,179,59.666667
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2,136,45.333333
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3,76,25.333333

In [15]:
df["Percentage_Score"] = df["Percentage_Score"].round(2)

In [16]:
df.head()

,StudentID,Name,Country,Gender,Age,Math_Score,Reading_Score,Writing_Score,School,Class,Total_Score,Percentage_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1,188,62.67
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2,187,62.33
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3,179,59.67
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2,136,45.33
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3,76,25.33

In [19]:
#Renaming column
df.rename(columns={"Math_Score": "Mathematics_Score"}, inplace=True)

In [26]:
df.head()

,StudentID,Name,Country,Gender,Age,Mathematics_Score,Reading_Score,Writing_Score,School,Class,Total_Score,Percentage_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,Nelson Mandela School,JSS1,188,62.67
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,Ubuntu Academy,JSS2,187,62.33
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,Ubuntu Academy,SS3,179,59.67
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,Ubuntu Academy,SS2,136,45.33
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,Ubuntu Academy,SS3,76,25.33

In [35]:
df.rename(columns={"Gender": "G"}, inplace=True)

In [36]:
df.head()

,StudentID,Name,Country,G,Age,Mathematics_Score,Reading_Score,Writing_Score,Class,Total_Score,Percentage_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,JSS1,188,62.67
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,JSS2,187,62.33
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,SS3,179,59.67
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,SS2,136,45.33
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,SS3,76,25.33

In [30]:
df.drop(columns=["School"], inplace=True)

In [31]:
df.head()

,StudentID,Name,Country,Gender,Age,Mathematics_Score,Reading_Score,Writing_Score,Class,Total_Score,Percentage_Score
0,1,Ifeanyi Mugisha,Zimbabwe,Female,18,99,77,12,JSS1,188,62.67
1,2,Yemi Okeke,Tanzania,Male,16,60,29,98,JSS2,187,62.33
2,3,Fatou Mugisha,Zimbabwe,Male,15,49,46,84,SS3,179,59.67
3,4,Chinedu Okafor,Ethiopia,Female,17,34,57,45,SS2,136,45.33
4,5,Yemi Moyo,Senegal,Male,16,22,16,38,SS3,76,25.33

In [45]:
df.to_csv('modified_student_score.csv', index=False)

In [49]:
df.to_html('modified_student_score.html', index=False)